package e.d.c.x.j;

import e.d.c.j;
import e.d.c.x.d;
import java.util.HashMap;

public class d extends d {
  protected static final HashMap<Integer, String> f = new HashMap<Integer, String>();
  
  protected static final HashMap<String, Integer> g = new HashMap<String, Integer>();
  
  static {
    HashMap<String, Integer> hashMap1 = g;
    Integer integer1 = Integer.valueOf(1280);
    hashMap1.put("com.apple.quicktime.album", integer1);
    HashMap<String, Integer> hashMap2 = g;
    Integer integer2 = Integer.valueOf(1281);
    hashMap2.put("com.apple.quicktime.artist", integer2);
    HashMap<String, Integer> hashMap3 = g;
    Integer integer3 = Integer.valueOf(1282);
    hashMap3.put("com.apple.quicktime.artwork", integer3);
    HashMap<String, Integer> hashMap4 = g;
    Integer integer4 = Integer.valueOf(1283);
    hashMap4.put("com.apple.quicktime.author", integer4);
    HashMap<String, Integer> hashMap5 = g;
    Integer integer5 = Integer.valueOf(1284);
    hashMap5.put("com.apple.quicktime.comment", integer5);
    HashMap<String, Integer> hashMap6 = g;
    Integer integer6 = Integer.valueOf(1285);
    hashMap6.put("com.apple.quicktime.copyright", integer6);
    hashMap6 = g;
    Integer integer7 = Integer.valueOf(1286);
    hashMap6.put("com.apple.quicktime.creationdate", integer7);
    g.put("com.apple.quicktime.description", Integer.valueOf(1287));
    g.put("com.apple.quicktime.director", Integer.valueOf(1288));
    g.put("com.apple.quicktime.title", Integer.valueOf(1289));
    g.put("com.apple.quicktime.genre", Integer.valueOf(1290));
    g.put("com.apple.quicktime.information", Integer.valueOf(1291));
    g.put("com.apple.quicktime.keywords", Integer.valueOf(1292));
    g.put("com.apple.quicktime.location.ISO6709", Integer.valueOf(1293));
    g.put("com.apple.quicktime.producer", Integer.valueOf(1294));
    g.put("com.apple.quicktime.publisher", Integer.valueOf(1295));
    g.put("com.apple.quicktime.software", Integer.valueOf(1296));
    g.put("com.apple.quicktime.year", Integer.valueOf(1297));
    g.put("com.apple.quicktime.collection.user", Integer.valueOf(1298));
    g.put("com.apple.quicktime.rating.user", Integer.valueOf(1299));
    g.put("com.apple.quicktime.location.name", Integer.valueOf(1300));
    g.put("com.apple.quicktime.location.body", Integer.valueOf(1301));
    g.put("com.apple.quicktime.location.note", Integer.valueOf(1302));
    g.put("com.apple.quicktime.location.role", Integer.valueOf(1303));
    g.put("com.apple.quicktime.location.date", Integer.valueOf(1304));
    g.put("com.apple.quicktime.direction.facing", Integer.valueOf(1305));
    g.put("com.apple.quicktime.direction.motion", Integer.valueOf(1306));
    g.put("com.apple.quicktime.displayname", Integer.valueOf(1307));
    g.put("com.apple.quicktime.content.identifier", Integer.valueOf(1308));
    g.put("com.apple.quicktime.make", Integer.valueOf(1309));
    g.put("com.apple.quicktime.model", Integer.valueOf(1310));
    g.put("com.apple.photos.originating.signature", Integer.valueOf(1311));
    g.put("----", Integer.valueOf(1024));
    g.put("@PST", Integer.valueOf(1025));
    g.put("@ppi", Integer.valueOf(1026));
    g.put("@pti", Integer.valueOf(1027));
    g.put("@sti", Integer.valueOf(1028));
    g.put("AACR", Integer.valueOf(1029));
    g.put("CDEK", Integer.valueOf(1030));
    g.put("CDET", Integer.valueOf(1031));
    g.put("GUID", Integer.valueOf(1032));
    g.put("VERS", Integer.valueOf(1033));
    g.put("aART", Integer.valueOf(1034));
    g.put("akID", Integer.valueOf(1035));
    g.put("albm", Integer.valueOf(1036));
    g.put("apID", Integer.valueOf(1037));
    g.put("atID", Integer.valueOf(1038));
    g.put("auth", Integer.valueOf(1039));
    g.put("catg", Integer.valueOf(1040));
    g.put("cnID", Integer.valueOf(1041));
    g.put("covr", Integer.valueOf(1042));
    g.put("cpil", Integer.valueOf(1043));
    g.put("cprt", Integer.valueOf(1044));
    g.put("desc", Integer.valueOf(1045));
    g.put("disk", Integer.valueOf(1046));
    g.put("dscp", Integer.valueOf(1047));
    g.put("egid", Integer.valueOf(1048));
    g.put("geID", Integer.valueOf(1049));
    g.put("gnre", Integer.valueOf(1050));
    g.put("grup", Integer.valueOf(1051));
    g.put("gshh", Integer.valueOf(1052));
    g.put("gspm", Integer.valueOf(1053));
    g.put("gspu", Integer.valueOf(1054));
    g.put("gssd", Integer.valueOf(1055));
    g.put("gsst", Integer.valueOf(1056));
    g.put("gstd", Integer.valueOf(1057));
    g.put("hdvd", Integer.valueOf(1058));
    g.put("itnu", Integer.valueOf(1059));
    g.put("keyw", Integer.valueOf(1060));
    g.put("ldes", Integer.valueOf(1061));
    g.put("pcst", Integer.valueOf(1062));
    g.put("perf", Integer.valueOf(1063));
    g.put("pgap", Integer.valueOf(1064));
    g.put("plID", Integer.valueOf(1065));
    g.put("prID", Integer.valueOf(1066));
    g.put("purd", Integer.valueOf(1067));
    g.put("purl", Integer.valueOf(1068));
    g.put("rate", Integer.valueOf(1069));
    g.put("rldt", Integer.valueOf(1070));
    g.put("rtng", Integer.valueOf(1071));
    g.put("sfID", Integer.valueOf(1072));
    g.put("soaa", Integer.valueOf(1073));
    g.put("soal", Integer.valueOf(1074));
    g.put("soar", Integer.valueOf(1075));
    g.put("soco", Integer.valueOf(1076));
    g.put("sonm", Integer.valueOf(1077));
    g.put("sosn", Integer.valueOf(1078));
    g.put("stik", Integer.valueOf(1079));
    g.put("titl", Integer.valueOf(1080));
    g.put("tmpo", Integer.valueOf(1081));
    g.put("trkn", Integer.valueOf(1082));
    g.put("tven", Integer.valueOf(1083));
    g.put("tves", Integer.valueOf(1084));
    g.put("tvnn", Integer.valueOf(1085));
    g.put("tvsh", Integer.valueOf(1086));
    g.put("tvsn", Integer.valueOf(1087));
    g.put("yrrc", Integer.valueOf(1088));
    g.put("�ART", Integer.valueOf(1089));
    g.put("�alb", Integer.valueOf(1090));
    g.put("�cmt", Integer.valueOf(1091));
    g.put("�com", Integer.valueOf(1092));
    g.put("�cpy", Integer.valueOf(1093));
    g.put("�day", Integer.valueOf(1094));
    g.put("�des", Integer.valueOf(1095));
    g.put("�enc", Integer.valueOf(1096));
    g.put("�gen", Integer.valueOf(1097));
    g.put("�grp", Integer.valueOf(1098));
    g.put("�lyr", Integer.valueOf(1099));
    g.put("�nam", Integer.valueOf(1100));
    g.put("�nrt", Integer.valueOf(1101));
    g.put("�pub", Integer.valueOf(1102));
    g.put("�too", Integer.valueOf(1103));
    g.put("�trk", Integer.valueOf(1104));
    g.put("�wrt", Integer.valueOf(1105));
    f.put(integer1, "Album");
    f.put(integer2, "Artist");
    f.put(integer3, "Artwork");
    f.put(integer4, "Author");
    f.put(integer5, "Comment");
    f.put(integer6, "Copyright");
    f.put(integer7, "Creation Date");
    f.put(Integer.valueOf(1287), "Description");
    f.put(Integer.valueOf(1288), "Director");
    f.put(Integer.valueOf(1289), "Title");
    f.put(Integer.valueOf(1290), "Genre");
    f.put(Integer.valueOf(1291), "Information");
    f.put(Integer.valueOf(1292), "Keywords");
    f.put(Integer.valueOf(1293), "ISO 6709");
    f.put(Integer.valueOf(1294), "Producer");
    f.put(Integer.valueOf(1295), "Publisher");
    f.put(Integer.valueOf(1296), "Software");
    f.put(Integer.valueOf(1297), "Year");
    f.put(Integer.valueOf(1298), "Collection User");
    f.put(Integer.valueOf(1299), "Rating User");
    f.put(Integer.valueOf(1300), "Location Name");
    f.put(Integer.valueOf(1301), "Location Body");
    f.put(Integer.valueOf(1302), "Location Note");
    f.put(Integer.valueOf(1303), "Location Role");
    f.put(Integer.valueOf(1304), "Location Date");
    f.put(Integer.valueOf(1305), "Direction Facing");
    f.put(Integer.valueOf(1306), "Direction Motion");
    f.put(Integer.valueOf(1307), "Display Name");
    f.put(Integer.valueOf(1308), "Content Identifier");
    f.put(Integer.valueOf(1309), "Make");
    f.put(Integer.valueOf(1310), "Model");
    f.put(Integer.valueOf(1311), "Originating Signature");
    f.put(Integer.valueOf(1024), "iTunes Info");
    f.put(Integer.valueOf(1025), "Parent Short Title");
    f.put(Integer.valueOf(1026), "Parent Product ID");
    f.put(Integer.valueOf(1027), "Parent Title");
    f.put(Integer.valueOf(1028), "Short Title");
    f.put(Integer.valueOf(1029), "Unknown_AACR?");
    f.put(Integer.valueOf(1030), "Unknown_CDEK?");
    f.put(Integer.valueOf(1031), "Unknown_CDET?");
    f.put(Integer.valueOf(1032), "GUID");
    f.put(Integer.valueOf(1033), "Product Version");
    f.put(Integer.valueOf(1034), "Album Artist");
    f.put(Integer.valueOf(1035), "Apple Store Account Type");
    f.put(Integer.valueOf(1036), "Album");
    f.put(Integer.valueOf(1037), "Apple Store Account");
    f.put(Integer.valueOf(1038), "Album Title ID");
    f.put(Integer.valueOf(1039), "Author");
    f.put(Integer.valueOf(1040), "Category");
    f.put(Integer.valueOf(1041), "Apple Store Catalog ID");
    f.put(Integer.valueOf(1042), "Cover Art");
    f.put(Integer.valueOf(1043), "Compilation");
    f.put(Integer.valueOf(1044), "Copyright");
    f.put(Integer.valueOf(1045), "Description");
    f.put(Integer.valueOf(1046), "Disk Number");
    f.put(Integer.valueOf(1047), "Description");
    f.put(Integer.valueOf(1048), "Episode Global Unique ID");
    f.put(Integer.valueOf(1049), "Genre ID");
    f.put(Integer.valueOf(1050), "Genre");
    f.put(Integer.valueOf(1051), "Grouping");
    f.put(Integer.valueOf(1052), "Google Host Header");
    f.put(Integer.valueOf(1053), "Google Ping Message");
    f.put(Integer.valueOf(1054), "Google Ping URL");
    f.put(Integer.valueOf(1055), "Google Source Data");
    f.put(Integer.valueOf(1056), "Google Start Time");
    f.put(Integer.valueOf(1057), "Google Track Duration");
    f.put(Integer.valueOf(1058), "HD Video");
    f.put(Integer.valueOf(1059), "iTunes U");
    f.put(Integer.valueOf(1060), "Keyword");
    f.put(Integer.valueOf(1061), "Long Description");
    f.put(Integer.valueOf(1062), "Podcast");
    f.put(Integer.valueOf(1063), "Performer");
    f.put(Integer.valueOf(1064), "Play Gap");
    f.put(Integer.valueOf(1065), "Play List ID");
    f.put(Integer.valueOf(1066), "Product ID");
    f.put(Integer.valueOf(1067), "Purchase Date");
    f.put(Integer.valueOf(1068), "Podcast URL");
    f.put(Integer.valueOf(1069), "Rating Percent");
    f.put(Integer.valueOf(1070), "Release Date");
    f.put(Integer.valueOf(1071), "Rating");
    f.put(Integer.valueOf(1072), "Apple Store Country");
    f.put(Integer.valueOf(1073), "Sort Album Artist");
    f.put(Integer.valueOf(1074), "Sort Album");
    f.put(Integer.valueOf(1075), "Sort Artist");
    f.put(Integer.valueOf(1076), "Sort Composer");
    f.put(Integer.valueOf(1077), "Sort Name");
    f.put(Integer.valueOf(1078), "Sort Show");
    f.put(Integer.valueOf(1079), "Media Type");
    f.put(Integer.valueOf(1080), "Title");
    f.put(Integer.valueOf(1081), "Beats Per Minute");
    f.put(Integer.valueOf(1082), "Track Number");
    f.put(Integer.valueOf(1083), "TV Episode ID");
    f.put(Integer.valueOf(1084), "TV Episode");
    f.put(Integer.valueOf(1085), "TV Network Name");
    f.put(Integer.valueOf(1086), "TV Show");
    f.put(Integer.valueOf(1087), "TV Season");
    f.put(Integer.valueOf(1088), "Year");
    f.put(Integer.valueOf(1089), "Artist");
    f.put(Integer.valueOf(1090), "Album");
    f.put(Integer.valueOf(1091), "Comment");
    f.put(Integer.valueOf(1092), "Composer");
    f.put(Integer.valueOf(1093), "Copyright");
    f.put(Integer.valueOf(1094), "Content Create Date");
    f.put(Integer.valueOf(1095), "Description");
    f.put(Integer.valueOf(1096), "Encoded By");
    f.put(Integer.valueOf(1097), "Genre");
    f.put(Integer.valueOf(1098), "Grouping");
    f.put(Integer.valueOf(1099), "Lyrics");
    f.put(Integer.valueOf(1100), "Title");
    f.put(Integer.valueOf(1101), "Narrator");
    f.put(Integer.valueOf(1102), "Publisher");
    f.put(Integer.valueOf(1103), "Encoder");
    f.put(Integer.valueOf(1104), "Track");
    f.put(Integer.valueOf(1105), "Composer");
  }
  
  public d() {
    a((j)new c(this));
  }
  
  public String a() {
    return "QuickTime Metadata";
  }
  
  protected HashMap<Integer, String> b() {
    return f;
  }
}


/* Location:              /home/yc/Downloads/LeaveHomeSafe.jar!/e/d/c/x/j/d.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */