package e.d.c.d0;

import e.d.c.b;
import java.util.HashMap;

public class b extends b {
  protected static final HashMap<Integer, String> e = new HashMap<Integer, String>();
  
  protected static final transient HashMap<String, Integer> f = new HashMap<String, Integer>();
  
  protected static final transient HashMap<Integer, String> g = new HashMap<Integer, String>();
  
  static {
    HashMap<String, Integer> hashMap1 = f;
    Integer integer1 = Integer.valueOf(7);
    hashMap1.put("IART", integer1);
    HashMap<String, Integer> hashMap2 = f;
    Integer integer2 = Integer.valueOf(8);
    hashMap2.put("INAM", integer2);
    HashMap<String, Integer> hashMap3 = f;
    Integer integer3 = Integer.valueOf(9);
    hashMap3.put("IPRD", integer3);
    HashMap<String, Integer> hashMap4 = f;
    Integer integer4 = Integer.valueOf(10);
    hashMap4.put("ITRK", integer4);
    HashMap<String, Integer> hashMap5 = f;
    Integer integer5 = Integer.valueOf(11);
    hashMap5.put("ICRD", integer5);
    HashMap<String, Integer> hashMap6 = f;
    Integer integer6 = Integer.valueOf(12);
    hashMap6.put("IGNR", integer6);
    hashMap6 = f;
    Integer integer7 = Integer.valueOf(13);
    hashMap6.put("ICMT", integer7);
    f.put("ICOP", Integer.valueOf(14));
    f.put("ISFT", Integer.valueOf(15));
    e.put(Integer.valueOf(1), "Format");
    e.put(Integer.valueOf(2), "Channels");
    e.put(Integer.valueOf(3), "Samples Per Second");
    e.put(Integer.valueOf(4), "Bytes Per Second");
    e.put(Integer.valueOf(5), "Block Alignment");
    e.put(Integer.valueOf(6), "Bits Per Sample");
    e.put(integer1, "Artist");
    e.put(integer2, "Title");
    e.put(integer3, "Product");
    e.put(integer4, "Track Number");
    e.put(integer5, "Date Created");
    e.put(integer6, "Genre");
    e.put(integer7, "Comments");
    e.put(Integer.valueOf(14), "Copyright");
    e.put(Integer.valueOf(15), "Software");
    e.put(Integer.valueOf(16), "Duration");
    g.put(Integer.valueOf(1), "Microsoft PCM");
    g.put(Integer.valueOf(2), "Microsoft ADPCM");
    g.put(Integer.valueOf(3), "Microsoft IEEE float");
    g.put(Integer.valueOf(4), "Compaq VSELP");
    g.put(Integer.valueOf(5), "IBM CVSD");
    g.put(Integer.valueOf(6), "Microsoft a-Law");
    g.put(integer1, "Microsoft u-Law");
    g.put(integer2, "Microsoft DTS");
    g.put(integer3, "DRM");
    g.put(integer4, "WMA 9 Speech");
    g.put(integer5, "Microsoft Windows Media RT Voice");
    g.put(Integer.valueOf(16), "OKI-ADPCM");
    g.put(Integer.valueOf(17), "Intel IMA/DVI-ADPCM");
    g.put(Integer.valueOf(18), "Videologic Mediaspace ADPCM");
    g.put(Integer.valueOf(19), "Sierra ADPCM");
    g.put(Integer.valueOf(20), "Antex G.723 ADPCM");
    g.put(Integer.valueOf(21), "DSP Solutions DIGISTD");
    g.put(Integer.valueOf(22), "DSP Solutions DIGIFIX");
    g.put(Integer.valueOf(23), "Dialoic OKI ADPCM");
    g.put(Integer.valueOf(24), "Media Vision ADPCM");
    g.put(Integer.valueOf(25), "HP CU");
    g.put(Integer.valueOf(26), "HP Dynamic Voice");
    g.put(Integer.valueOf(32), "Yamaha ADPCM");
    g.put(Integer.valueOf(33), "SONARC Speech Compression");
    g.put(Integer.valueOf(34), "DSP Group True Speech");
    g.put(Integer.valueOf(35), "Echo Speech Corp.");
    g.put(Integer.valueOf(36), "Virtual Music Audiofile AF36");
    g.put(Integer.valueOf(37), "Audio Processing Tech.");
    g.put(Integer.valueOf(38), "Virtual Music Audiofile AF10");
    g.put(Integer.valueOf(39), "Aculab Prosody 1612");
    g.put(Integer.valueOf(40), "Merging Tech. LRC");
    g.put(Integer.valueOf(48), "Dolby AC2");
    g.put(Integer.valueOf(49), "Microsoft GSM610");
    g.put(Integer.valueOf(50), "MSN Audio");
    g.put(Integer.valueOf(51), "Antex ADPCME");
    g.put(Integer.valueOf(52), "Control Resources VQLPC");
    g.put(Integer.valueOf(53), "DSP Solutions DIGIREAL");
    g.put(Integer.valueOf(54), "DSP Solutions DIGIADPCM");
    g.put(Integer.valueOf(55), "Control Resources CR10");
    g.put(Integer.valueOf(56), "Natural MicroSystems VBX ADPCM");
    g.put(Integer.valueOf(57), "Crystal Semiconductor IMA ADPCM");
    g.put(Integer.valueOf(58), "Echo Speech ECHOSC3");
    g.put(Integer.valueOf(59), "Rockwell ADPCM");
    g.put(Integer.valueOf(60), "Rockwell DIGITALK");
    g.put(Integer.valueOf(61), "Xebec Multimedia");
    g.put(Integer.valueOf(64), "Antex G.721 ADPCM");
    g.put(Integer.valueOf(65), "Antex G.728 CELP");
    g.put(Integer.valueOf(66), "Microsoft MSG723");
    g.put(Integer.valueOf(67), "IBM AVC ADPCM");
    g.put(Integer.valueOf(69), "ITU-T G.726");
    g.put(Integer.valueOf(80), "Microsoft MPEG");
    g.put(Integer.valueOf(81), "RT23 or PAC");
    g.put(Integer.valueOf(82), "InSoft RT24");
    g.put(Integer.valueOf(83), "InSoft PAC");
    g.put(Integer.valueOf(85), "MP3");
    g.put(Integer.valueOf(89), "Cirrus");
    g.put(Integer.valueOf(96), "Cirrus Logic");
    g.put(Integer.valueOf(97), "ESS Tech. PCM");
    g.put(Integer.valueOf(98), "Voxware Inc.");
    g.put(Integer.valueOf(99), "Canopus ATRAC");
    g.put(Integer.valueOf(100), "APICOM G.726 ADPCM");
    g.put(Integer.valueOf(101), "APICOM G.722 ADPCM");
    g.put(Integer.valueOf(102), "Microsoft DSAT");
    g.put(Integer.valueOf(103), "Micorsoft DSAT DISPLAY");
    g.put(Integer.valueOf(105), "Voxware Byte Aligned");
    g.put(Integer.valueOf(112), "Voxware AC8");
    g.put(Integer.valueOf(113), "Voxware AC10");
    g.put(Integer.valueOf(114), "Voxware AC16");
    g.put(Integer.valueOf(115), "Voxware AC20");
    g.put(Integer.valueOf(116), "Voxware MetaVoice");
    g.put(Integer.valueOf(117), "Voxware MetaSound");
    g.put(Integer.valueOf(118), "Voxware RT29HW");
    g.put(Integer.valueOf(119), "Voxware VR12");
    g.put(Integer.valueOf(120), "Voxware VR18");
    g.put(Integer.valueOf(121), "Voxware TQ40");
    g.put(Integer.valueOf(122), "Voxware SC3");
    g.put(Integer.valueOf(123), "Voxware SC3");
    g.put(Integer.valueOf(128), "Soundsoft");
    g.put(Integer.valueOf(129), "Voxware TQ60");
    g.put(Integer.valueOf(130), "Microsoft MSRT24");
    g.put(Integer.valueOf(131), "AT&T G.729A");
    g.put(Integer.valueOf(132), "Motion Pixels MVI MV12");
    g.put(Integer.valueOf(133), "DataFusion G.726");
    g.put(Integer.valueOf(134), "DataFusion GSM610");
    g.put(Integer.valueOf(136), "Iterated Systems Audio");
    g.put(Integer.valueOf(137), "Onlive");
    g.put(Integer.valueOf(138), "Multitude, Inc. FT SX20");
    g.put(Integer.valueOf(139), "Infocom ITS A/S G.721 ADPCM");
    g.put(Integer.valueOf(140), "Convedia G729");
    g.put(Integer.valueOf(141), "Not specified congruency, Inc.");
    g.put(Integer.valueOf(145), "Siemens SBC24");
    g.put(Integer.valueOf(146), "Sonic Foundry Dolby AC3 APDIF");
    g.put(Integer.valueOf(147), "MediaSonic G.723");
    g.put(Integer.valueOf(148), "Aculab Prosody 8kbps");
    g.put(Integer.valueOf(151), "ZyXEL ADPCM");
    g.put(Integer.valueOf(152), "Philips LPCBB");
    g.put(Integer.valueOf(153), "Studer Professional Audio Packed");
    g.put(Integer.valueOf(160), "Malden PhonyTalk");
    g.put(Integer.valueOf(161), "Racal Recorder GSM");
    g.put(Integer.valueOf(162), "Racal Recorder G720.a");
    g.put(Integer.valueOf(163), "Racal G723.1");
    g.put(Integer.valueOf(164), "Racal Tetra ACELP");
    g.put(Integer.valueOf(176), "NEC AAC NEC Corporation");
    g.put(Integer.valueOf(255), "AAC");
    g.put(Integer.valueOf(256), "Rhetorex ADPCM");
    g.put(Integer.valueOf(257), "IBM u-Law");
    g.put(Integer.valueOf(258), "IBM a-Law");
    g.put(Integer.valueOf(259), "IBM ADPCM");
    g.put(Integer.valueOf(273), "Vivo G.723");
    g.put(Integer.valueOf(274), "Vivo Siren");
    g.put(Integer.valueOf(288), "Philips Speech Processing CELP");
    g.put(Integer.valueOf(289), "Philips Speech Processing GRUNDIG");
    g.put(Integer.valueOf(291), "Digital G.723");
    g.put(Integer.valueOf(293), "Sanyo LD ADPCM");
    g.put(Integer.valueOf(304), "Sipro Lab ACEPLNET");
    g.put(Integer.valueOf(305), "Sipro Lab ACELP4800");
    g.put(Integer.valueOf(306), "Sipro Lab ACELP8V3");
    g.put(Integer.valueOf(307), "Sipro Lab G.729");
    g.put(Integer.valueOf(308), "Sipro Lab G.729A");
    g.put(Integer.valueOf(309), "Sipro Lab Kelvin");
    g.put(Integer.valueOf(310), "VoiceAge AMR");
    g.put(Integer.valueOf(320), "Dictaphone G.726 ADPCM");
    g.put(Integer.valueOf(336), "Qualcomm PureVoice");
    g.put(Integer.valueOf(337), "Qualcomm HalfRate");
    g.put(Integer.valueOf(341), "Ring Zero Systems TUBGSM");
    g.put(Integer.valueOf(352), "Microsoft Audio1");
    g.put(Integer.valueOf(353), "Windows Media Audio V2 V7 V8 V9 / DivX audio (WMA) / Alex AC3 Audio");
    g.put(Integer.valueOf(354), "Windows Media Audio Professional V9");
    g.put(Integer.valueOf(355), "Windows Media Audio Lossless V9");
    g.put(Integer.valueOf(356), "WMA Pro over S/PDIF");
    g.put(Integer.valueOf(368), "UNISYS NAP ADPCM");
    g.put(Integer.valueOf(369), "UNISYS NAP ULAW");
    g.put(Integer.valueOf(370), "UNISYS NAP ALAW");
    g.put(Integer.valueOf(371), "UNISYS NAP 16K");
    g.put(Integer.valueOf(372), "MM SYCOM ACM SYC008 SyCom Technologies");
    g.put(Integer.valueOf(373), "MM SYCOM ACM SYC701 G726L SyCom Technologies");
    g.put(Integer.valueOf(374), "MM SYCOM ACM SYC701 CELP54 SyCom Technologies");
    g.put(Integer.valueOf(375), "MM SYCOM ACM SYC701 CELP68 SyCom Technologies");
    g.put(Integer.valueOf(376), "Knowledge Adventure ADPCM");
    g.put(Integer.valueOf(384), "Fraunhofer IIS MPEG2AAC");
    g.put(Integer.valueOf(400), "Digital Theater Systems DTS DS");
    g.put(Integer.valueOf(512), "Creative Labs ADPCM");
    g.put(Integer.valueOf(514), "Creative Labs FASTSPEECH8");
    g.put(Integer.valueOf(515), "Creative Labs FASTSPEECH10");
    g.put(Integer.valueOf(528), "UHER ADPCM");
    g.put(Integer.valueOf(533), "Ulead DV ACM");
    g.put(Integer.valueOf(534), "Ulead DV ACM");
    g.put(Integer.valueOf(544), "Quarterdeck Corp.");
    g.put(Integer.valueOf(560), "I-Link VC");
    g.put(Integer.valueOf(576), "Aureal Semiconductor Raw Sport");
    g.put(Integer.valueOf(577), "ESST AC3");
    g.put(Integer.valueOf(592), "Interactive Products HSX");
    g.put(Integer.valueOf(593), "Interactive Products RPELP");
    g.put(Integer.valueOf(608), "Consistent CS2");
    g.put(Integer.valueOf(624), "Sony SCX");
    g.put(Integer.valueOf(625), "Sony SCY");
    g.put(Integer.valueOf(626), "Sony ATRAC3");
    g.put(Integer.valueOf(627), "Sony SPC");
    g.put(Integer.valueOf(640), "TELUM Telum Inc.");
    g.put(Integer.valueOf(641), "TELUMIA Telum Inc.");
    g.put(Integer.valueOf(645), "Norcom Voice Systems ADPCM");
    g.put(Integer.valueOf(768), "Fujitsu FM TOWNS SND");
    g.put(Integer.valueOf(769), "Fujitsu (not specified)");
    g.put(Integer.valueOf(770), "Fujitsu (not specified)");
    g.put(Integer.valueOf(771), "Fujitsu (not specified)");
    g.put(Integer.valueOf(772), "Fujitsu (not specified)");
    g.put(Integer.valueOf(773), "Fujitsu (not specified)");
    g.put(Integer.valueOf(774), "Fujitsu (not specified)");
    g.put(Integer.valueOf(775), "Fujitsu (not specified)");
    g.put(Integer.valueOf(776), "Fujitsu (not specified)");
    g.put(Integer.valueOf(848), "Micronas Semiconductors, Inc. Development");
    g.put(Integer.valueOf(849), "Micronas Semiconductors, Inc. CELP833");
    g.put(Integer.valueOf(1024), "Brooktree Digital");
    g.put(Integer.valueOf(1025), "Intel Music Coder (IMC)");
    g.put(Integer.valueOf(1026), "Ligos Indeo Audio");
    g.put(Integer.valueOf(1104), "QDesign Music");
    g.put(Integer.valueOf(1280), "On2 VP7 On2 Technologies");
    g.put(Integer.valueOf(1281), "On2 VP6 On2 Technologies");
    g.put(Integer.valueOf(1664), "AT&T VME VMPCM");
    g.put(Integer.valueOf(1665), "AT&T TCP");
    g.put(Integer.valueOf(1792), "YMPEG Alpha (dummy for MPEG-2 compressor)");
    g.put(Integer.valueOf(2222), "ClearJump LiteWave (lossless)");
    g.put(Integer.valueOf(4096), "Olivetti GSM");
    g.put(Integer.valueOf(4097), "Olivetti ADPCM");
    g.put(Integer.valueOf(4098), "Olivetti CELP");
    g.put(Integer.valueOf(4099), "Olivetti SBC");
    g.put(Integer.valueOf(4100), "Olivetti OPR");
    g.put(Integer.valueOf(4352), "Lernout & Hauspie");
    g.put(Integer.valueOf(4353), "Lernout & Hauspie CELP codec");
    g.put(Integer.valueOf(4354), "Lernout & Hauspie SBC codec");
    g.put(Integer.valueOf(4355), "Lernout & Hauspie SBC codec");
    g.put(Integer.valueOf(4356), "Lernout & Hauspie SBC codec");
    g.put(Integer.valueOf(5120), "Norris Comm. Inc.");
    g.put(Integer.valueOf(5121), "ISIAudio");
    g.put(Integer.valueOf(5376), "AT&T Soundspace Music Compression");
    g.put(Integer.valueOf(6172), "VoxWare RT24 speech codec");
    g.put(Integer.valueOf(6174), "Lucent elemedia AX24000P Music codec");
    g.put(Integer.valueOf(6513), "Sonic Foundry LOSSLESS");
    g.put(Integer.valueOf(6521), "Innings Telecom Inc. ADPCM");
    g.put(Integer.valueOf(7175), "Lucent SX8300P speech codec");
    g.put(Integer.valueOf(7180), "Lucent SX5363S G.723 compliant codec");
    g.put(Integer.valueOf(7939), "CUseeMe DigiTalk (ex-Rocwell)");
    g.put(Integer.valueOf(8132), "NCT Soft ALF2CD ACM");
    g.put(Integer.valueOf(8192), "FAST Multimedia DVM");
    g.put(Integer.valueOf(8193), "Dolby DTS (Digital Theater System)");
    g.put(Integer.valueOf(8194), "RealAudio 1 / 2 14.4");
    g.put(Integer.valueOf(8195), "RealAudio 1 / 2 28.8");
    g.put(Integer.valueOf(8196), "RealAudio G2 / 8 Cook (low bitrate)");
    g.put(Integer.valueOf(8197), "RealAudio 3 / 4 / 5 Music (DNET)");
    g.put(Integer.valueOf(8198), "RealAudio 10 AAC (RAAC)");
    g.put(Integer.valueOf(8199), "RealAudio 10 AAC+ (RACP)");
    g.put(Integer.valueOf(9472), "Reserved range to 0x2600 Microsoft");
    g.put(Integer.valueOf(13075), "makeAVIS (ffvfw fake AVI sound from AviSynth scripts)");
    g.put(Integer.valueOf(16707), "Divio MPEG-4 AAC audio");
    g.put(Integer.valueOf(16897), "Nokia adaptive multirate");
    g.put(Integer.valueOf(16963), "Divio G726 Divio, Inc.");
    g.put(Integer.valueOf(17228), "LEAD Speech");
    g.put(Integer.valueOf(22092), "LEAD Vorbis");
    g.put(Integer.valueOf(22358), "WavPack Audio");
    g.put(Integer.valueOf(26447), "Ogg Vorbis (mode 1)");
    g.put(Integer.valueOf(26448), "Ogg Vorbis (mode 2)");
    g.put(Integer.valueOf(26449), "Ogg Vorbis (mode 3)");
    g.put(Integer.valueOf(26479), "Ogg Vorbis (mode 1+)");
    g.put(Integer.valueOf(26480), "Ogg Vorbis (mode 2+)");
    g.put(Integer.valueOf(26481), "Ogg Vorbis (mode 3+)");
    g.put(Integer.valueOf(28672), "3COM NBX 3Com Corporation");
    g.put(Integer.valueOf(28781), "FAAD AAC");
    g.put(Integer.valueOf(31265), "GSM-AMR (CBR, no SID)");
    g.put(Integer.valueOf(31266), "GSM-AMR (VBR, including SID)");
    g.put(Integer.valueOf(41216), "Comverse Infosys Ltd. G723 1");
    g.put(Integer.valueOf(41217), "Comverse Infosys Ltd. AVQSBC");
    g.put(Integer.valueOf(41218), "Comverse Infosys Ltd. OLDSBC");
    g.put(Integer.valueOf(41219), "Symbol Technologies G729A");
    g.put(Integer.valueOf(41220), "VoiceAge AMR WB VoiceAge Corporation");
    g.put(Integer.valueOf(41221), "Ingenient Technologies Inc. G726");
    g.put(Integer.valueOf(41222), "ISO/MPEG-4 advanced audio Coding");
    g.put(Integer.valueOf(41223), "Encore Software Ltd G726");
    g.put(Integer.valueOf(41225), "Speex ACM Codec xiph.org");
    g.put(Integer.valueOf(57260), "DebugMode SonicFoundry Vegas FrameServer ACM Codec");
    g.put(Integer.valueOf(59144), "Unknown -");
    g.put(Integer.valueOf(61868), "Free Lossless Audio Codec FLAC");
    g.put(Integer.valueOf(65534), "Extensible");
    g.put(Integer.valueOf(65535), "Development");
  }
  
  public b() {
    a(new a(this));
  }
  
  public String a() {
    return "WAV";
  }
  
  protected HashMap<Integer, String> b() {
    return e;
  }
}


/* Location:              /home/yc/Downloads/LeaveHomeSafe.jar!/e/d/c/d0/b.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */