package com.facebook.react.bridge;

public enum ReactMarkerConstants {
  ATTACH_MEASURED_ROOT_VIEWS_END, ATTACH_MEASURED_ROOT_VIEWS_START, BUILD_NATIVE_MODULE_REGISTRY_END, BUILD_NATIVE_MODULE_REGISTRY_START, BUILD_REACT_INSTANCE_MANAGER_END, BUILD_REACT_INSTANCE_MANAGER_START, CHANGE_THREAD_PRIORITY, CONTENT_APPEARED, CONVERT_CONSTANTS_END, CONVERT_CONSTANTS_START, CREATE_CATALYST_INSTANCE_END, CREATE_CATALYST_INSTANCE_START, CREATE_I18N_ASSETS_MODULE_END, CREATE_I18N_ASSETS_MODULE_START, CREATE_I18N_MODULE_CONSTANTS_END, CREATE_I18N_MODULE_CONSTANTS_START, CREATE_MC_MODULE_END, CREATE_MC_MODULE_GET_METADATA_END, CREATE_MC_MODULE_GET_METADATA_START, CREATE_MC_MODULE_START, CREATE_MODULE_END, CREATE_MODULE_START, CREATE_REACT_CONTEXT_END, CREATE_REACT_CONTEXT_START, CREATE_UI_MANAGER_MODULE_CONSTANTS_END, CREATE_UI_MANAGER_MODULE_CONSTANTS_START, CREATE_UI_MANAGER_MODULE_END, CREATE_UI_MANAGER_MODULE_START, CREATE_VIEW_MANAGERS_END, CREATE_VIEW_MANAGERS_START, DESTROY_CATALYST_INSTANCE_END, DESTROY_CATALYST_INSTANCE_START, DOWNLOAD_END, DOWNLOAD_START, FABRIC_BATCH_EXECUTION_END, FABRIC_BATCH_EXECUTION_START, FABRIC_COMMIT_END, FABRIC_COMMIT_START, FABRIC_DIFF_END, FABRIC_DIFF_START, FABRIC_FINISH_TRANSACTION_END, FABRIC_FINISH_TRANSACTION_START, FABRIC_LAYOUT_END, FABRIC_LAYOUT_START, FABRIC_UPDATE_UI_MAIN_THREAD_END, FABRIC_UPDATE_UI_MAIN_THREAD_START, GET_CONSTANTS_END, GET_CONSTANTS_START, GET_REACT_INSTANCE_HOLDER_SPEC_END, GET_REACT_INSTANCE_HOLDER_SPEC_START, GET_REACT_INSTANCE_MANAGER_END, GET_REACT_INSTANCE_MANAGER_START, I18N_MODULE_CONSTANTS_CONVERT_END, I18N_MODULE_CONSTANTS_CONVERT_START, INITIALIZE_MODULE_END, INITIALIZE_MODULE_START, JAVASCRIPT_EXECUTOR_FACTORY_INJECT_END, JAVASCRIPT_EXECUTOR_FACTORY_INJECT_START, LOAD_REACT_NATIVE_FABRIC_SO_FILE_END, LOAD_REACT_NATIVE_FABRIC_SO_FILE_START, LOAD_REACT_NATIVE_SO_FILE_END, LOAD_REACT_NATIVE_SO_FILE_START, NATIVE_MODULE_INITIALIZE_END, NATIVE_MODULE_INITIALIZE_START, NATIVE_MODULE_SETUP_END, NATIVE_MODULE_SETUP_START, ON_FRAGMENT_CREATE, ON_HOST_PAUSE_END, ON_HOST_PAUSE_START, ON_HOST_RESUME_END, ON_HOST_RESUME_START, PRE_REACT_CONTEXT_END, PRE_RUN_JS_BUNDLE_START, PRE_SETUP_REACT_CONTEXT_END, PRE_SETUP_REACT_CONTEXT_START, PROCESS_CORE_REACT_PACKAGE_END, PROCESS_CORE_REACT_PACKAGE_START, PROCESS_INFRA_PACKAGE_END, PROCESS_INFRA_PACKAGE_START, PROCESS_PACKAGES_END, PROCESS_PACKAGES_START, PROCESS_PRODUCT_PACKAGE_END, PROCESS_PRODUCT_PACKAGE_START, REACT_CONTEXT_THREAD_END, REACT_CONTEXT_THREAD_START, REGISTER_JS_SEGMENT_START, REGISTER_JS_SEGMENT_STOP, RELOAD, RUN_JS_BUNDLE_END, RUN_JS_BUNDLE_START, SETUP_REACT_CONTEXT_END, SETUP_REACT_CONTEXT_START, UNPACKING_JS_BUNDLE_LOADER_BLOCKED, UNPACKING_JS_BUNDLE_LOADER_CHECK_END, UNPACKING_JS_BUNDLE_LOADER_CHECK_START, UNPACKING_JS_BUNDLE_LOADER_EXTRACTED, VM_INIT, loadApplicationScript_endStringConvert, loadApplicationScript_startStringConvert;
  
  static {
    CREATE_REACT_CONTEXT_END = new ReactMarkerConstants("CREATE_REACT_CONTEXT_END", 1);
    PROCESS_PACKAGES_START = new ReactMarkerConstants("PROCESS_PACKAGES_START", 2);
    PROCESS_PACKAGES_END = new ReactMarkerConstants("PROCESS_PACKAGES_END", 3);
    BUILD_NATIVE_MODULE_REGISTRY_START = new ReactMarkerConstants("BUILD_NATIVE_MODULE_REGISTRY_START", 4);
    BUILD_NATIVE_MODULE_REGISTRY_END = new ReactMarkerConstants("BUILD_NATIVE_MODULE_REGISTRY_END", 5);
    CREATE_CATALYST_INSTANCE_START = new ReactMarkerConstants("CREATE_CATALYST_INSTANCE_START", 6);
    CREATE_CATALYST_INSTANCE_END = new ReactMarkerConstants("CREATE_CATALYST_INSTANCE_END", 7);
    DESTROY_CATALYST_INSTANCE_START = new ReactMarkerConstants("DESTROY_CATALYST_INSTANCE_START", 8);
    DESTROY_CATALYST_INSTANCE_END = new ReactMarkerConstants("DESTROY_CATALYST_INSTANCE_END", 9);
    RUN_JS_BUNDLE_START = new ReactMarkerConstants("RUN_JS_BUNDLE_START", 10);
    RUN_JS_BUNDLE_END = new ReactMarkerConstants("RUN_JS_BUNDLE_END", 11);
    NATIVE_MODULE_INITIALIZE_START = new ReactMarkerConstants("NATIVE_MODULE_INITIALIZE_START", 12);
    NATIVE_MODULE_INITIALIZE_END = new ReactMarkerConstants("NATIVE_MODULE_INITIALIZE_END", 13);
    SETUP_REACT_CONTEXT_START = new ReactMarkerConstants("SETUP_REACT_CONTEXT_START", 14);
    SETUP_REACT_CONTEXT_END = new ReactMarkerConstants("SETUP_REACT_CONTEXT_END", 15);
    CHANGE_THREAD_PRIORITY = new ReactMarkerConstants("CHANGE_THREAD_PRIORITY", 16);
    CREATE_UI_MANAGER_MODULE_START = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_START", 17);
    CREATE_UI_MANAGER_MODULE_END = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_END", 18);
    CREATE_VIEW_MANAGERS_START = new ReactMarkerConstants("CREATE_VIEW_MANAGERS_START", 19);
    CREATE_VIEW_MANAGERS_END = new ReactMarkerConstants("CREATE_VIEW_MANAGERS_END", 20);
    CREATE_UI_MANAGER_MODULE_CONSTANTS_START = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_CONSTANTS_START", 21);
    CREATE_UI_MANAGER_MODULE_CONSTANTS_END = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_CONSTANTS_END", 22);
    NATIVE_MODULE_SETUP_START = new ReactMarkerConstants("NATIVE_MODULE_SETUP_START", 23);
    NATIVE_MODULE_SETUP_END = new ReactMarkerConstants("NATIVE_MODULE_SETUP_END", 24);
    CREATE_MODULE_START = new ReactMarkerConstants("CREATE_MODULE_START", 25);
    CREATE_MODULE_END = new ReactMarkerConstants("CREATE_MODULE_END", 26);
    PROCESS_CORE_REACT_PACKAGE_START = new ReactMarkerConstants("PROCESS_CORE_REACT_PACKAGE_START", 27);
    PROCESS_CORE_REACT_PACKAGE_END = new ReactMarkerConstants("PROCESS_CORE_REACT_PACKAGE_END", 28);
    CREATE_I18N_MODULE_CONSTANTS_START = new ReactMarkerConstants("CREATE_I18N_MODULE_CONSTANTS_START", 29);
    CREATE_I18N_MODULE_CONSTANTS_END = new ReactMarkerConstants("CREATE_I18N_MODULE_CONSTANTS_END", 30);
    I18N_MODULE_CONSTANTS_CONVERT_START = new ReactMarkerConstants("I18N_MODULE_CONSTANTS_CONVERT_START", 31);
    I18N_MODULE_CONSTANTS_CONVERT_END = new ReactMarkerConstants("I18N_MODULE_CONSTANTS_CONVERT_END", 32);
    CREATE_I18N_ASSETS_MODULE_START = new ReactMarkerConstants("CREATE_I18N_ASSETS_MODULE_START", 33);
    CREATE_I18N_ASSETS_MODULE_END = new ReactMarkerConstants("CREATE_I18N_ASSETS_MODULE_END", 34);
    GET_CONSTANTS_START = new ReactMarkerConstants("GET_CONSTANTS_START", 35);
    GET_CONSTANTS_END = new ReactMarkerConstants("GET_CONSTANTS_END", 36);
    INITIALIZE_MODULE_START = new ReactMarkerConstants("INITIALIZE_MODULE_START", 37);
    INITIALIZE_MODULE_END = new ReactMarkerConstants("INITIALIZE_MODULE_END", 38);
    ON_HOST_RESUME_START = new ReactMarkerConstants("ON_HOST_RESUME_START", 39);
    ON_HOST_RESUME_END = new ReactMarkerConstants("ON_HOST_RESUME_END", 40);
    ON_HOST_PAUSE_START = new ReactMarkerConstants("ON_HOST_PAUSE_START", 41);
    ON_HOST_PAUSE_END = new ReactMarkerConstants("ON_HOST_PAUSE_END", 42);
    CONVERT_CONSTANTS_START = new ReactMarkerConstants("CONVERT_CONSTANTS_START", 43);
    CONVERT_CONSTANTS_END = new ReactMarkerConstants("CONVERT_CONSTANTS_END", 44);
    PRE_REACT_CONTEXT_END = new ReactMarkerConstants("PRE_REACT_CONTEXT_END", 45);
    UNPACKING_JS_BUNDLE_LOADER_CHECK_START = new ReactMarkerConstants("UNPACKING_JS_BUNDLE_LOADER_CHECK_START", 46);
    UNPACKING_JS_BUNDLE_LOADER_CHECK_END = new ReactMarkerConstants("UNPACKING_JS_BUNDLE_LOADER_CHECK_END", 47);
    UNPACKING_JS_BUNDLE_LOADER_EXTRACTED = new ReactMarkerConstants("UNPACKING_JS_BUNDLE_LOADER_EXTRACTED", 48);
    UNPACKING_JS_BUNDLE_LOADER_BLOCKED = new ReactMarkerConstants("UNPACKING_JS_BUNDLE_LOADER_BLOCKED", 49);
    loadApplicationScript_startStringConvert = new ReactMarkerConstants("loadApplicationScript_startStringConvert", 50);
    loadApplicationScript_endStringConvert = new ReactMarkerConstants("loadApplicationScript_endStringConvert", 51);
    PRE_SETUP_REACT_CONTEXT_START = new ReactMarkerConstants("PRE_SETUP_REACT_CONTEXT_START", 52);
    PRE_SETUP_REACT_CONTEXT_END = new ReactMarkerConstants("PRE_SETUP_REACT_CONTEXT_END", 53);
    PRE_RUN_JS_BUNDLE_START = new ReactMarkerConstants("PRE_RUN_JS_BUNDLE_START", 54);
    ATTACH_MEASURED_ROOT_VIEWS_START = new ReactMarkerConstants("ATTACH_MEASURED_ROOT_VIEWS_START", 55);
    ATTACH_MEASURED_ROOT_VIEWS_END = new ReactMarkerConstants("ATTACH_MEASURED_ROOT_VIEWS_END", 56);
    CONTENT_APPEARED = new ReactMarkerConstants("CONTENT_APPEARED", 57);
    RELOAD = new ReactMarkerConstants("RELOAD", 58);
    DOWNLOAD_START = new ReactMarkerConstants("DOWNLOAD_START", 59);
    DOWNLOAD_END = new ReactMarkerConstants("DOWNLOAD_END", 60);
    REACT_CONTEXT_THREAD_START = new ReactMarkerConstants("REACT_CONTEXT_THREAD_START", 61);
    REACT_CONTEXT_THREAD_END = new ReactMarkerConstants("REACT_CONTEXT_THREAD_END", 62);
    GET_REACT_INSTANCE_MANAGER_START = new ReactMarkerConstants("GET_REACT_INSTANCE_MANAGER_START", 63);
    GET_REACT_INSTANCE_MANAGER_END = new ReactMarkerConstants("GET_REACT_INSTANCE_MANAGER_END", 64);
    GET_REACT_INSTANCE_HOLDER_SPEC_START = new ReactMarkerConstants("GET_REACT_INSTANCE_HOLDER_SPEC_START", 65);
    GET_REACT_INSTANCE_HOLDER_SPEC_END = new ReactMarkerConstants("GET_REACT_INSTANCE_HOLDER_SPEC_END", 66);
    BUILD_REACT_INSTANCE_MANAGER_START = new ReactMarkerConstants("BUILD_REACT_INSTANCE_MANAGER_START", 67);
    BUILD_REACT_INSTANCE_MANAGER_END = new ReactMarkerConstants("BUILD_REACT_INSTANCE_MANAGER_END", 68);
    PROCESS_INFRA_PACKAGE_START = new ReactMarkerConstants("PROCESS_INFRA_PACKAGE_START", 69);
    PROCESS_INFRA_PACKAGE_END = new ReactMarkerConstants("PROCESS_INFRA_PACKAGE_END", 70);
    PROCESS_PRODUCT_PACKAGE_START = new ReactMarkerConstants("PROCESS_PRODUCT_PACKAGE_START", 71);
    PROCESS_PRODUCT_PACKAGE_END = new ReactMarkerConstants("PROCESS_PRODUCT_PACKAGE_END", 72);
    CREATE_MC_MODULE_START = new ReactMarkerConstants("CREATE_MC_MODULE_START", 73);
    CREATE_MC_MODULE_END = new ReactMarkerConstants("CREATE_MC_MODULE_END", 74);
    CREATE_MC_MODULE_GET_METADATA_START = new ReactMarkerConstants("CREATE_MC_MODULE_GET_METADATA_START", 75);
    CREATE_MC_MODULE_GET_METADATA_END = new ReactMarkerConstants("CREATE_MC_MODULE_GET_METADATA_END", 76);
    REGISTER_JS_SEGMENT_START = new ReactMarkerConstants("REGISTER_JS_SEGMENT_START", 77);
    REGISTER_JS_SEGMENT_STOP = new ReactMarkerConstants("REGISTER_JS_SEGMENT_STOP", 78);
    VM_INIT = new ReactMarkerConstants("VM_INIT", 79);
    ON_FRAGMENT_CREATE = new ReactMarkerConstants("ON_FRAGMENT_CREATE", 80);
    JAVASCRIPT_EXECUTOR_FACTORY_INJECT_START = new ReactMarkerConstants("JAVASCRIPT_EXECUTOR_FACTORY_INJECT_START", 81);
    JAVASCRIPT_EXECUTOR_FACTORY_INJECT_END = new ReactMarkerConstants("JAVASCRIPT_EXECUTOR_FACTORY_INJECT_END", 82);
    LOAD_REACT_NATIVE_SO_FILE_START = new ReactMarkerConstants("LOAD_REACT_NATIVE_SO_FILE_START", 83);
    LOAD_REACT_NATIVE_SO_FILE_END = new ReactMarkerConstants("LOAD_REACT_NATIVE_SO_FILE_END", 84);
    LOAD_REACT_NATIVE_FABRIC_SO_FILE_START = new ReactMarkerConstants("LOAD_REACT_NATIVE_FABRIC_SO_FILE_START", 85);
    LOAD_REACT_NATIVE_FABRIC_SO_FILE_END = new ReactMarkerConstants("LOAD_REACT_NATIVE_FABRIC_SO_FILE_END", 86);
    FABRIC_COMMIT_START = new ReactMarkerConstants("FABRIC_COMMIT_START", 87);
    FABRIC_COMMIT_END = new ReactMarkerConstants("FABRIC_COMMIT_END", 88);
    FABRIC_FINISH_TRANSACTION_START = new ReactMarkerConstants("FABRIC_FINISH_TRANSACTION_START", 89);
    FABRIC_FINISH_TRANSACTION_END = new ReactMarkerConstants("FABRIC_FINISH_TRANSACTION_END", 90);
    FABRIC_DIFF_START = new ReactMarkerConstants("FABRIC_DIFF_START", 91);
    FABRIC_DIFF_END = new ReactMarkerConstants("FABRIC_DIFF_END", 92);
    FABRIC_LAYOUT_START = new ReactMarkerConstants("FABRIC_LAYOUT_START", 93);
    FABRIC_LAYOUT_END = new ReactMarkerConstants("FABRIC_LAYOUT_END", 94);
    FABRIC_BATCH_EXECUTION_START = new ReactMarkerConstants("FABRIC_BATCH_EXECUTION_START", 95);
    FABRIC_BATCH_EXECUTION_END = new ReactMarkerConstants("FABRIC_BATCH_EXECUTION_END", 96);
    FABRIC_UPDATE_UI_MAIN_THREAD_START = new ReactMarkerConstants("FABRIC_UPDATE_UI_MAIN_THREAD_START", 97);
    FABRIC_UPDATE_UI_MAIN_THREAD_END = new ReactMarkerConstants("FABRIC_UPDATE_UI_MAIN_THREAD_END", 98);
    $VALUES = new ReactMarkerConstants[] { 
        CREATE_REACT_CONTEXT_START, CREATE_REACT_CONTEXT_END, PROCESS_PACKAGES_START, PROCESS_PACKAGES_END, BUILD_NATIVE_MODULE_REGISTRY_START, BUILD_NATIVE_MODULE_REGISTRY_END, CREATE_CATALYST_INSTANCE_START, CREATE_CATALYST_INSTANCE_END, DESTROY_CATALYST_INSTANCE_START, DESTROY_CATALYST_INSTANCE_END, 
        RUN_JS_BUNDLE_START, RUN_JS_BUNDLE_END, NATIVE_MODULE_INITIALIZE_START, NATIVE_MODULE_INITIALIZE_END, SETUP_REACT_CONTEXT_START, SETUP_REACT_CONTEXT_END, CHANGE_THREAD_PRIORITY, CREATE_UI_MANAGER_MODULE_START, CREATE_UI_MANAGER_MODULE_END, CREATE_VIEW_MANAGERS_START, 
        CREATE_VIEW_MANAGERS_END, CREATE_UI_MANAGER_MODULE_CONSTANTS_START, CREATE_UI_MANAGER_MODULE_CONSTANTS_END, NATIVE_MODULE_SETUP_START, NATIVE_MODULE_SETUP_END, CREATE_MODULE_START, CREATE_MODULE_END, PROCESS_CORE_REACT_PACKAGE_START, PROCESS_CORE_REACT_PACKAGE_END, CREATE_I18N_MODULE_CONSTANTS_START, 
        CREATE_I18N_MODULE_CONSTANTS_END, I18N_MODULE_CONSTANTS_CONVERT_START, I18N_MODULE_CONSTANTS_CONVERT_END, CREATE_I18N_ASSETS_MODULE_START, CREATE_I18N_ASSETS_MODULE_END, GET_CONSTANTS_START, GET_CONSTANTS_END, INITIALIZE_MODULE_START, INITIALIZE_MODULE_END, ON_HOST_RESUME_START, 
        ON_HOST_RESUME_END, ON_HOST_PAUSE_START, ON_HOST_PAUSE_END, CONVERT_CONSTANTS_START, CONVERT_CONSTANTS_END, PRE_REACT_CONTEXT_END, UNPACKING_JS_BUNDLE_LOADER_CHECK_START, UNPACKING_JS_BUNDLE_LOADER_CHECK_END, UNPACKING_JS_BUNDLE_LOADER_EXTRACTED, UNPACKING_JS_BUNDLE_LOADER_BLOCKED, 
        loadApplicationScript_startStringConvert, loadApplicationScript_endStringConvert, PRE_SETUP_REACT_CONTEXT_START, PRE_SETUP_REACT_CONTEXT_END, PRE_RUN_JS_BUNDLE_START, ATTACH_MEASURED_ROOT_VIEWS_START, ATTACH_MEASURED_ROOT_VIEWS_END, CONTENT_APPEARED, RELOAD, DOWNLOAD_START, 
        DOWNLOAD_END, REACT_CONTEXT_THREAD_START, REACT_CONTEXT_THREAD_END, GET_REACT_INSTANCE_MANAGER_START, GET_REACT_INSTANCE_MANAGER_END, GET_REACT_INSTANCE_HOLDER_SPEC_START, GET_REACT_INSTANCE_HOLDER_SPEC_END, BUILD_REACT_INSTANCE_MANAGER_START, BUILD_REACT_INSTANCE_MANAGER_END, PROCESS_INFRA_PACKAGE_START, 
        PROCESS_INFRA_PACKAGE_END, PROCESS_PRODUCT_PACKAGE_START, PROCESS_PRODUCT_PACKAGE_END, CREATE_MC_MODULE_START, CREATE_MC_MODULE_END, CREATE_MC_MODULE_GET_METADATA_START, CREATE_MC_MODULE_GET_METADATA_END, REGISTER_JS_SEGMENT_START, REGISTER_JS_SEGMENT_STOP, VM_INIT, 
        ON_FRAGMENT_CREATE, JAVASCRIPT_EXECUTOR_FACTORY_INJECT_START, JAVASCRIPT_EXECUTOR_FACTORY_INJECT_END, LOAD_REACT_NATIVE_SO_FILE_START, LOAD_REACT_NATIVE_SO_FILE_END, LOAD_REACT_NATIVE_FABRIC_SO_FILE_START, LOAD_REACT_NATIVE_FABRIC_SO_FILE_END, FABRIC_COMMIT_START, FABRIC_COMMIT_END, FABRIC_FINISH_TRANSACTION_START, 
        FABRIC_FINISH_TRANSACTION_END, FABRIC_DIFF_START, FABRIC_DIFF_END, FABRIC_LAYOUT_START, FABRIC_LAYOUT_END, FABRIC_BATCH_EXECUTION_START, FABRIC_BATCH_EXECUTION_END, FABRIC_UPDATE_UI_MAIN_THREAD_START, FABRIC_UPDATE_UI_MAIN_THREAD_END };
  }
}


/* Location:              /home/yc/Downloads/LeaveHomeSafe.jar!/com/facebook/react/bridge/ReactMarkerConstants.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */